### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#19]
As a user I want to select a date range so that I can more easily select dates without interacting with multiple date pickers

AC:  
- Ability to select a start date
- Ability to select an end date.
- be able to span multiple calendars (so that the start can be 7-29 and end date 8-5)

**Comment by lindseyo1123** [comment]
requirements from Diana

For the reverse button, we are looking to create some sort of button that will reverse the input for two auro-input components. This would behave identically to the reverse button on google flights. <- / ->

We also need to be able to show the lowest price per day to match the design blueprint: https://www.figma.com/file/r0xy9TpWpR0AQ6to1dQ9gY/Date-Picker?node-id=322%3A298&t=CQF0zYk0mOsoi9Wn-0

**Comment by lindseyo1123** [comment]
Reverse button would be a separate component and request. June & Kayla will be working on this. It could be a variant to auro-button that just allows for an icon only within a button, final design tbd.

**Comment by blackfalcon** [comment]
Refinement discussion focused on completing the design file in preparation for engineering. 

The 1st iteration calendar does not support a date range feature. There is another 3rd party calendar that we can look into that supports this out of the box and we need to do a POC in order to determine the next steps to support the new scope of the element. 

@blackfalcon will create the POC stories for engineering and the story for @leeejune to complete the design specs.

**Comment by blackfalcon** [comment]
Closing this issue. The description has been moved to the [milestone](https://github.com/AlaskaAirlines/auro-datepicker/milestone/2).
