### ISSUE TITLE
UX for `calendarStartDate` and `calendarEndDate` should be revisited

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-datepicker#231]
### Please verify the version of auro-datepicker you have installed

2.6.0

### Please describe the bug

The current implementation of calendarStartDate and calendarEndDate only affect the dates rendered and navigated to. They do not impact what dates may be selected.

This means that a user can type a date that is outside of the `calendarStartDate` and `calendarEndDate`. When they do so, the calendar will jump to the month they typed. But the next/prev buttons are controlled seperately which means a user can type a date that is several months before the `calendarStartDate`, navigate forward in time some months, but not return back to the month they typed (since the previous month button is disabled due to the range of `calendarStartDate`).

1. Go to running demo of datepicker (either localhost or docsite)
2. Go to API page
3. Scroll to `calendarStartDate` & `calendarEndDate` example
4. Click into the input and type `02/02/2023`
5. See that calendar jumps to the date even when its outside of the range and only left arrow shows up to navigate to previous months)

### Reproducing the error

This issue is reproducible on the Auro docsite

### What browsers are you seeing the problem on?

Chrome

### Exit criteria

This issue can be considered done once the team discusses the correct UI behavior for this issue and that is resolved.

**Comment by jason-capsule42** [comment]
I have updated the description of this ticket to be a little more clear what the issue here is.

Also, my proposed improvement would be the following:

- calendarStart/End dates continue to control what the boundary of the calendar months that can be rendered. If the implementer uses these attributes then they are explicitly choosing to set the boundary of calendar months they want a user to be able to view. In almost all cases this is likely used in combination with min/max dates.
- In the unlikely scenario that the implementer sets a calendarStartDate without a minDate and a user manually enters a value earlier than the calendarStartDate, we should accept the value as valid but not navigate the viewed calendar month since the implement has used the attributes to explicitly say those months are not to be rendered.
