### ISSUE TITLE
auro-combobox not taking required parameter

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-datepicker#37]
## Describe the bug

auro-combobox is not taking the required parameter. Even though we pass it, it still says optional.

## To Reproduce

1. Go to 'test env link below'
2. You should see in the planbook combobox the "(optional)" inside even though we are passing the required parameter.

## Expected behavior

The expected behavior should be that we don't have the "(optional)" in the search box

![Screen Shot 2022-08-01 at 9 54 51 AM](https://user-images.githubusercontent.com/108018885/182202421-6aa97cab-31d4-480e-8525-351e88aa1a5b.png)

## Desktop (please complete the following information):

 - OS: [MacOS]
 - Browser [chrome, firefox]

## Additional context
[Code Link](https://github.com/Alaska-ECommerce/flightsearch-lem-svelte/blob/main/src/lib/planbook/CitiesDates.svelte#L84)
[Testing Env](https://www.alaskaair.com/search-test/)

**Comment by jesussilverioea** [comment]
having required={true} solve the issue.

**Comment by blackfalcon** [comment]
@jesussilverioea what framework is this you are working in? React or Svelte? 

Keep in mind, HTML booleans are not `true` or `false`. Many boolean attributes will simply use the existence of the attribute as `true` and the absence as `undefined`. According to the HTML spec, the actual definition of this is `disabled="disabled"`. Also, `disabled="false"` is also `true` because the attribute is present. 

Different frameworks see these HTML boolean values differently. 

For your case, I would also try `disabled={disabled}` and I would assume that would work as expected and this would be more reflective of the actual HTML state.
