### ISSUE TITLE
Mobile Designs - Datepicker

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#85]
## Is your feature request related to a problem? Please describe.

As a user I want to have components to interact with that are optimized for the mobile platform.  We need to identify the specific changes needed to be implemented to date picker in order to match the designs.

## Acceptance Criteria
- Create an issue(s) for each design element that needs to be implemented.
- What other components need a similar update?  Create corresponding stories and figma designs for each of those.
- Create a milestone for all of this work in github.  If there are multiple components that will need to be updated use the same milestone name so we can link them on our board.

**Comment by leeejune** [comment]
[Datepicker blueprint](https://www.figma.com/file/r0xy9TpWpR0AQ6to1dQ9gY/Date-Picker?node-id=322%3A298)

**Comment by leeejune** [comment]
https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?node-id=1839%3A23843&t=HMREBAOYbCrLtm1Q-1

After discussing with Auro devs, I've added the following notes in the blueprint.
- The text above the calendar is static and aims to indicate what date the user has selected.
- Accessibility research has been done prior to the design work, and users did not struggle using the current date picker on mobile.
- Visually impaired users don't use mobile date pickers because of bad experiences with other date pickers on mobile.

Next steps are to come up with a development plan.

**Comment by jason-capsule42** [comment]
@leeejune Engineering approves design. Ticket for code work opened. #107
